// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterinariaMVC.Data;

#nullable disable

namespace VeterinariaMVC.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260923215732_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeterinariaMVC.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Especies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Canino"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Felino"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Ave"
                        });
                });

            modelBuilder.Entity("VeterinariaMVC.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdPropietario")
                        .HasColumnType("int");

                    b.Property<int>("IdRaza")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RutaFoto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdPropietario");

                    b.HasIndex("IdRaza");

                    b.ToTable("Mascotas", (string)null);
                });

            modelBuilder.Entity("VeterinariaMVC.Models.Propietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Propietarios", (string)null);
                });

            modelBuilder.Entity("VeterinariaMVC.Models.Raza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEspecie")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdEspecie");

                    b.ToTable("Razas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdEspecie = 1,
                            Nombre = "Labrador Retriever"
                        },
                        new
                        {
                            Id = 2,
                            IdEspecie = 1,
                            Nombre = "Pastor Alemán"
                        },
                        new
                        {
                            Id = 3,
                            IdEspecie = 1,
                            Nombre = "Bulldog Francés"
                        },
                        new
                        {
                            Id = 4,
                            IdEspecie = 1,
                            Nombre = "Criollo"
                        },
                        new
                        {
                            Id = 5,
                            IdEspecie = 2,
                            Nombre = "Siamés"
                        },
                        new
                        {
                            Id = 6,
                            IdEspecie = 2,
                            Nombre = "Persa"
                        },
                        new
                        {
                            Id = 7,
                            IdEspecie = 2,
                            Nombre = "Angora"
                        },
                        new
                        {
                            Id = 8,
                            IdEspecie = 3,
                            Nombre = "Periquito"
                        },
                        new
                        {
                            Id = 9,
                            IdEspecie = 3,
                            Nombre = "Canario"
                        });
                });

            modelBuilder.Entity("VeterinariaMVC.Models.Mascota", b =>
                {
                    b.HasOne("VeterinariaMVC.Models.Propietario", "Propietario")
                        .WithMany("Mascotas")
                        .HasForeignKey("IdPropietario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeterinariaMVC.Models.Raza", "Raza")
                        .WithMany("Mascotas")
                        .HasForeignKey("IdRaza")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Propietario");

                    b.Navigation("Raza");
                });

            modelBuilder.Entity("VeterinariaMVC.Models.Raza", b =>
                {
                    b.HasOne("VeterinariaMVC.Models.Especie", "Especie")
                        .WithMany("Razas")
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("VeterinariaMVC.Models.Especie", b =>
                {
                    b.Navigation("Razas");
                });

            modelBuilder.Entity("VeterinariaMVC.Models.Propietario", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("VeterinariaMVC.Models.Raza", b =>
                {
                    b.Navigation("Mascotas");
                });
#pragma warning restore 612, 618
        }
    }
}
